site_name: Портфолио курса "Программирование на Python" и не только

nav:
  - Home: index.md
  - About: about.md
  - Labs:
      - Lab №1: labs/lab1.md
      - Lab №2: labs/lab2.md
      - Lab №3: labs/lab3.md

theme:
  name: readthedocs
  custom_dir: docs/templates
  locale: ru

plugins:
  - search
  - markupsafe-markdown-filter